apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-v1
spec:
  replicas: 9
  selector:
    matchLabels:
      app: portfolio
      version: v1
  template:
    metadata:
      labels:
        app: portfolio
        version: v1
    spec:
      containers:
        - name: app
          image: 381492065975.dkr.ecr.ap-south-1.amazonaws.com/personal-portfolio:1.0
          ports:
            - containerPort: 8080

