apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
      version: v2
  template:
    metadata:
      labels:
        app: portfolio
        version: v2
    spec:
      containers:
        - name: app
          image: 381492065975.dkr.ecr.ap-south-1.amazonaws.com/personal-portfolio:2.0
          ports:
            - containerPort: 8080

